## ================================================================================================
## Makefile für Projektverwaltung
## ================================================================================================

PROJECT = level_test

include ../../sim/$(PROJECT)/makefile.sources

SOURCE_FILES = $(SYN_SOURCE_FILES)

include ../makefile
