## ================================================================================================
## Makefile für Projektverwaltung
## ================================================================================================

PROJECT = uart_rx

include ../../sim/$(PROJECT)/makefile.sources

SOURCE_FILES = $(SYN_SOURCE_FILES)

include ../makefile
