## ================================================================================================
## Makefile für Projektverwaltung
## ================================================================================================

PROJECT = ledsw

SYN_SOURCE_FILES = ../../src/ledsw.v

SOURCE_FILES = $(SYN_SOURCE_FILES)

include ../makefile
