## ================================================================================================
## Makefile für Projektverwaltung
## ================================================================================================

PROJECT = npxl_treiber

include ../../sim/$(PROJECT)/makefile.sources

SOURCE_FILES = $(SYN_SOURCE_FILES)

include ../makefile
