## ================================================================================================
## Makefile für Projektverwaltung
## ================================================================================================

PROJECT = npxl_treiber

include ../../sim/npxl_treiber/makefile.sources

SOURCE_FILES = $(SYN_SOURCE_FILES)

include ../makefile
