## ================================================================================================
## Makefile für Projektverwaltung
## ================================================================================================

PROJECT = npxl_controller

include ../../sim/npxl_controller/makefile.sources

SOURCE_FILES = $(SYN_SOURCE_FILES)

include ../makefile
